In [ ]:
        loss = torch.pow(torch.norm(x, dim=(2,3)), 2)
        return torch.mean(loss,1)

In [1]:
import torch

In [2]:
a=torch.rand(16,4,10,10)

In [7]:
a

tensor([[[[0.5069, 0.8580, 0.9679,  ..., 0.6572, 0.8356, 0.0021],
          [0.4662, 0.8322, 0.1630,  ..., 0.8270, 0.0522, 0.7179],
          [0.6786, 0.0394, 0.0614,  ..., 0.0647, 0.5487, 0.4567],
          ...,
          [0.9320, 0.8454, 0.8390,  ..., 0.0950, 0.9022, 0.8748],
          [0.0691, 0.5484, 0.6642,  ..., 0.8939, 0.9622, 0.1953],
          [0.9498, 0.1054, 0.0036,  ..., 0.4123, 0.9975, 0.6248]],

         [[0.7624, 0.1771, 0.3323,  ..., 0.7977, 0.7713, 0.7604],
          [0.9770, 0.2643, 0.5608,  ..., 0.2385, 0.7716, 0.3054],
          [0.0215, 0.9513, 0.8492,  ..., 0.6763, 0.1049, 0.0196],
          ...,
          [0.2339, 0.8433, 0.6863,  ..., 0.0716, 0.4026, 0.9849],
          [0.3446, 0.9089, 0.1997,  ..., 0.1872, 0.3419, 0.9184],
          [0.8172, 0.4558, 0.9555,  ..., 0.6780, 0.7557, 0.5901]],

         [[0.7563, 0.9756, 0.6819,  ..., 0.9278, 0.8772, 0.2242],
          [0.6071, 0.7607, 0.0148,  ..., 0.1097, 0.3197, 0.6097],
          [0.2327, 0.6141, 0.8254,  ..., 0

In [11]:
torch.norm(a, dim=(2,3))

tensor([[5.9069, 5.8956, 5.8761, 5.6530],
        [5.6892, 5.8449, 5.6462, 5.2743],
        [5.9470, 6.0367, 5.6313, 5.8782],
        [5.4494, 5.9750, 5.8143, 5.5985],
        [5.8215, 5.7613, 5.6255, 5.8478],
        [6.0079, 5.9687, 5.7489, 5.8929],
        [5.4947, 5.7253, 5.7918, 6.3265],
        [5.7365, 5.7211, 5.3890, 5.6375],
        [5.4886, 5.7336, 5.8294, 5.5044],
        [5.8871, 5.3245, 5.9121, 5.4196],
        [6.0948, 6.0686, 5.3882, 6.1403],
        [5.7640, 5.4053, 6.2353, 5.8251],
        [5.3486, 5.5330, 5.7464, 6.0188],
        [5.3829, 5.7063, 5.6249, 5.3918],
        [5.7367, 5.9485, 5.9842, 5.6595],
        [5.7923, 6.2031, 5.9427, 5.7038]])

In [4]:
loss = torch.pow(torch.norm(a, dim=(2,3)), 2)

In [5]:
torch.mean(loss,1)

tensor([34.0333, 31.5570, 34.5186, 32.6363, 33.2313, 34.8740, 34.1352, 31.6153,
        31.8194, 31.8335, 35.1776, 33.8130, 32.1172, 30.5620, 34.0338, 34.9691])

In [6]:
torch.mean(torch.mean(loss,1))

tensor(33.1829)

In [16]:
b=torch.tensor([[1.,2.,3.],[4.,5.,6.]])

In [19]:
torch.norm(b,dim=0)

tensor([4.1231, 5.3852, 6.7082])

In [20]:
4.1231*4.1231

16.99995361